SET SERVEROUTPUT ON;
EXEC ADMIN.MANAGE_CART_AND_ORDERS.CREATE_CART(1);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.CREATE_CART(2);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.ADD_CART_ITEM(1,'BUDWISER',50);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.ADD_CART_ITEM(2,'BUDWISER',50);

SET SERVEROUTPUT ON;
EXEC ADMIN.MANAGE_CART_AND_ORDERS.CREATE_ORDER(1, 101);

SET SERVEROUTPUT ON;
SET FEEDBACK OFF;
EXEC ADMIN.MANAGE_CART_AND_ORDERS.CREATE_ORDER(2, 102);

COMMIT;

select * from cart;
select * from cart_item;
select * from orders;
select * from order_item;
select * from product;