SET SERVEROUTPUT ON;

EXEC DROP_ALL_TABLES;
EXEC CREATE_ALL_TABLES;
EXEC INSERT_ALL_TABLES;

-- Check
EXEC DELETE_CART_ORDERS;

EXEC INSERT_USERS_AND_ROLES;

GRANT CONNECT TO CUSTOMER_2;
GRANT CONNECT TO SUPPLIER_1;

GRANT CREATE SESSION  TO  CUSTOMER_1;
GRANT CREATE SESSION  TO  CUSTOMER_2;
GRANT CREATE SESSION  TO  SUPPLIER_1;

GRANT EXECUTE ON MANAGE_CART_AND_ORDERS TO CUSTOMER_1;
GRANT EXECUTE ON MANAGE_CART_AND_ORDERS TO CUSTOMER_2;

COMMIT;
