SET SERVEROUTPUT ON;

EXEC MANAGE_PRODUCT_SUPPLIER.ADD_NEW_PRODUCT('AASHAY', 1, 0, 1, 3);
EXEC MANAGE_PRODUCT_SUPPLIER.UPDATE_PRODUCT_NAME('YOGA MAT', 'YOGA MAT 2.0');
EXEC MANAGE_PRODUCT_SUPPLIER.UPDATE_PRODUCT_QTY('TIDE', 20);
EXEC MANAGE_PRODUCT_SUPPLIER.UPDATE_PRODUCT_PRICE('BUDWISER', 5);

SELECT * FROM PRODUCT;