SET SERVEROUTPUT ON;
EXEC ADMIN.MANAGE_CART_AND_ORDERS.CREATE_CART(1);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.CREATE_CART(2);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.ADD_CART_ITEM(1,'BUDWISER',50);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.ADD_CART_ITEM(1,'MM',13);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.ADD_CART_ITEM(2,'YOGA MAT',19);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.ADD_CART_ITEM(2,'SPOONS',10);

SET SERVEROUTPUT ON;
EXEC ADMIN.MANAGE_CART_AND_ORDERS.CREATE_ORDER(1, 101);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.ADD_ORDER_ITEMS(1);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.DELETE_CART_ITEM(1);

SET SERVEROUTPUT ON;
EXEC ADMIN.MANAGE_CART_AND_ORDERS.CREATE_ORDER(2, 102);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.ADD_ORDER_ITEMS(2);
EXEC ADMIN.MANAGE_CART_AND_ORDERS.DELETE_CART_ITEM(2);

COMMIT;