SELECT * FROM USER_TABLE;

SELECT * FROM ADDRESS;
SELECT * FROM CART;
SELECT * FROM ORDERS;
SELECT * FROM LOYALTY_DISCOUNT;

SELECT * FROM CART_ITEM;
SELECT * FROM ORDER_ITEM;

SELECT * FROM PRODUCT;

SELECT * FROM SUPPLIER;
SELECT * FROM DISCOUNT;
SELECT * FROM CATEGORY;
SELECT * FROM FEEDBACKS;