create or replace PROCEDURE DELETE_CART_ORDERS IS
M_LOOP_COUNT  INT;
BEGIN
    SELECT COUNT(*) INTO M_LOOP_COUNT FROM CART_ITEM;
    FOR I IN 1..M_LOOP_COUNT+1
        LOOP
            DELETE FROM CART_ITEM WHERE ROWNUM = 1;
        END LOOP;
        
    SELECT COUNT(*) INTO M_LOOP_COUNT FROM ORDER_ITEM;
    FOR I IN 1..M_LOOP_COUNT+1
        LOOP
            DELETE FROM ORDER_ITEM WHERE ROWNUM = 1;
        END LOOP;
        
    SELECT COUNT(*) INTO M_LOOP_COUNT FROM PAYMENT_INFO;
    FOR I IN 1..M_LOOP_COUNT+1
        LOOP
            DELETE FROM PAYMENT_INFO WHERE ROWNUM = 1;
        END LOOP; 

    SELECT COUNT(*) INTO M_LOOP_COUNT FROM CART;
    FOR I IN 1..M_LOOP_COUNT+1
        LOOP
            DELETE FROM CART WHERE ROWNUM = 1;
        END LOOP;

    SELECT COUNT(*) INTO M_LOOP_COUNT FROM ORDERS;
    FOR I IN 1..M_LOOP_COUNT+1
        LOOP
            DELETE FROM ORDERS WHERE ROWNUM = 1;
        END LOOP;      
    
    DBMS_OUTPUT.PUT_LINE('CART AND ORDERS DATA CLEARED');
END;