create or replace PROCEDURE DROP_ALL_TABLES IS
BEGIN
    FOR I IN (SELECT * FROM DBA_TABLES WHERE OWNER='ADMIN') LOOP
        EXECUTE IMMEDIATE ('DROP TABLE '||I.TABLE_NAME||' CASCADE CONSTRAINTS');
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('ANY TABLES IF EXISTED DELETED');
END;