SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE INSERT_USERS_AND_ROLES AS 
BEGIN
    EXECUTE IMMEDIATE('DROP USER AASHAYPAWAR');
    EXECUTE IMMEDIATE('DROP USER AKZLIMITED');
    EXECUTE IMMEDIATE('DROP ROLE CUSTOMER');
    EXECUTE IMMEDIATE('DROP ROLE SUPPLIER');
    
    MANAGE_USERS_AND_ACCESS.CREATE_ROLE('CUSTOMER');
    MANAGE_USERS_AND_ACCESS.MANAGE_ROLE_ACCESS('USER_TABLE','CUSTOMER','SELECT');
    MANAGE_USERS_AND_ACCESS.CREATE_USER('AASHAYPAWAR','Aashay@123456');
    MANAGE_USERS_AND_ACCESS.GRANT_ROLE_TO_USER('CUSTOMER','AASHAYPAWAR');
    
    MANAGE_USERS_AND_ACCESS.CREATE_ROLE('SUPPLIER');
    MANAGE_USERS_AND_ACCESS.MANAGE_ROLE_ACCESS('SUPPLIER','SUPPLIER','SELECT');
    MANAGE_USERS_AND_ACCESS.CREATE_USER('AKZLIMITED','Akzlimited@123456');
    MANAGE_USERS_AND_ACCESS.GRANT_ROLE_TO_USER('SUPPLIER','AKZLIMITED');
    
    EXECUTE IMMEDIATE('GRANT CREATE SESSION TO AASHAYPAWAR');
    EXECUTE IMMEDIATE('GRANT CREATE SESSION TO AKZLIMITED');
END;