-- TRUNCATE CHILDS: ORDER_ITEM, CART_ITEM, PAYMENT_INFO TABLES
-- TRUNCATE PARENTS: CART, ORDERS TABLES
EXEC DELETE_CART_ORDERS;


-- CHECK CART TABLE, INITIALLY NO ROWS
-- ADD A CART
-- CHECK CART TABLE
SELECT * FROM CART;
EXEC MANAGE_CART_AND_ORDERS.CREATE_CART(1);
SELECT * FROM CART;


-- CHECK CART_ITEM TABLE, INITIALLY NO ROWS
-- CHECK PRODUCT QTYS, INITIALLY 10 FOR TIDE AND 78 FOR BUDWISER
-- INSERT TIDE 2 QTYS
-- INSERT BUDWISER 5 QTYS
-- CHECK CART_ITEM TABLE
-- CHECK PRODUCT TABLE FOR UPDATED QTYS
SELECT * FROM CART_ITEM;
SELECT * FROM PRODUCT;
EXEC MANAGE_CART_AND_ORDERS.ADD_CART_ITEM(1,'TIDE',2);
EXEC MANAGE_CART_AND_ORDERS.ADD_CART_ITEM(1,'BUDWISER',5);
SELECT * FROM CART_ITEM;
SELECT * FROM PRODUCT;


-- CHECK ORDERS TABLE, INITIALLY NO ROWS
-- ADD ORDER
-- CHECK ORDERS TABLE
SELECT * FROM ORDERS;
EXEC MANAGE_CART_AND_ORDERS.CREATE_ORDER(1,101);
SELECT * FROM ORDERS;


-- CHECK ORDER_ITEM TABLE, INITIALLY NO ROWS
-- ADD ORDER ITEMS
-- CHECK ORDER_ITEM TABLE
SELECT * FROM ORDER_ITEM;
EXEC MANAGE_CART_AND_ORDERS.ADD_ORDER_ITEMS(1);
SELECT * FROM ORDER_ITEM;


-- CHECK CART_ITEM TABLE, INITIALLY 4 ROWS
-- DELETE ROWS FROM CART_ITEM
-- CHECK CART_ITEM TABLE
EXEC MANAGE_CART_AND_ORDERS.DELETE_CART_ITEM(1);
SELECT * FROM CART_ITEM;
