create or replace PACKAGE MANAGE_PRODUCT_SUPPLIER AS

PROCEDURE ADD_NEW_PRODUCT(PRODUCT_NAME VARCHAR, CATEGORY_ID INT, PRICE INT, QTY INT, DISCOUNT_ID FLOAT);
PROCEDURE UPDATE_PRODUCT_NAME(PRODUCT_NAME VARCHAR, NEW_PRODUCT_NAME VARCHAR);
PROCEDURE UPDATE_PRODUCT_QTY(PRODUCT_NAME VARCHAR, NEW_PRODUCT_QTY INT);
PROCEDURE UPDATE_PRODUCT_PRICE(PRODUCT_NAME VARCHAR, NEW_PRODUCT_PRICE INT);

END;