create or replace PACKAGE MANAGE_CART_AND_ORDERS AS

PROCEDURE CREATE_CART(USER_ID INT);

PROCEDURE ADD_CART_ITEM(
USER_ID INT
,PRODUCT_NAME VARCHAR
,QTY INT
);



/*PROCEDURE ADD_TO_CART(
CI_CART_ID INT
,CI_USER_ID INT
);
*/

PROCEDURE CREATE_ORDER( USER_ID INT, ADDRESS_ID INT);

/*PROCEDURE ADD_ORDER(
OI_ORDER_ID INT
,OI_ORDER_STATUS VARCHAR
,OI_USER_ID INT
,OI_ORDER_DATE date
,OI_ADDRESS_ID INT
);
*/
PROCEDURE ADD_ORDER_ITEMS(USER_ID INT);
--OI_ORDER_ITEM_ID INT
---,OI_ORDER_ID INT
--,OI_PRODUCT_ID INT
--,OI_QTY INT
--*/

PROCEDURE DELETE_CART_ITEM(USER_ID INT);

END;