create or replace PACKAGE MANAGE_USERS_AND_ACCESS AS
    PROCEDURE CREATE_USER (
        USERNAME VARCHAR,
        PASSWORD VARCHAR
    );

    PROCEDURE CREATE_ROLE (
        ROLENAME VARCHAR
    );

    PROCEDURE MANAGE_ROLE_ACCESS (
        TABLENAME   VARCHAR,
        ROLENAME    VARCHAR,
        ACCESSTYPES VARCHAR
    );

    PROCEDURE GRANT_ROLE_TO_USER (
        ROLENAME VARCHAR,
        USERNAME VARCHAR
    );

    FUNCTION F_IS_USER_ALREADY_CREATED (
        USERNAME VARCHAR
    ) RETURN NUMBER;

END;